## Q1. Create a null vector of size (3,3) but the value at (first row, second column) as 5
hint: use np.zeros 

In [ ]:
import numpy as np
v = np.zeros((3,3))
v[0,1] = 5
print (v)

[[0. 5. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Q2. Create a 10x10 array with random values and find the minimum/maximum/mean values

hint: .min(), .max(), .mean()

In [ ]:
x = np.random.randint(20, size=(10,10))
print(x)
print(x.min())
print(x.max())
print(x.mean())

[[ 8 17 17  4  5  0 14 11  0 11]
 [11 10  4  9  5  0  1 15 16 18]
 [ 4  3 14 16 16 18  9  6 15  7]
 [11  9 19 15  5 14 19  1  8 13]
 [18  3 18  4  0  4 18  2 10  7]
 [ 9  5 16 12  2  4 12  8 16 13]
 [11  2  6 14 19 19  1 12  9  7]
 [ 8 17  8  7  1  1 10 18  3 16]
 [11 12 14 14  6 15  3 11 16  0]
 [13 19 15  8 15 17 18 19 10  5]]
0
19
10.09


## Q3. Run the code below and discuss the results 

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


* 1st: No matter what mathematical function you do with nan, it returns as nan since it stands for a missing value
* 2nd: Since nan is a special floating point integer it cannot equate to itself or other forms of data like str int or float
* 3rd: Since np.nan is not defined, it cannot be deterimined if it is less than, greater than, or equal to 0
* 4th: No matter what mathematical function you do with nan, it returns as nan since it stands for a missing value, even when using it against itself.
* 5th: Though nan cannot equal nan, it is nan and can be found with the nan value set since it is conserved in functions
* 6th: Float are hard to == integer types in mathematical functions since the computer operates under a log function that may cause a very small difference in values

# Q4. Normalize a 5x5 random matrix 

hint: (x -mean)/std

In [ ]:
import numpy as np

x = np.random.randint(10, size=(5,5))
print (x)
y = x.mean()
z = x.std()
print((x-y)/z)

[[6 8 8 5 5]
 [5 1 5 4 3]
 [0 9 9 0 2]
 [8 0 1 4 5]
 [4 6 4 1 0]]
[[ 0.65391403  1.34956726  1.34956726  0.30608742  0.30608742]
 [ 0.30608742 -1.08521903  0.30608742 -0.04173919 -0.38956581]
 [-1.43304565  1.69739387  1.69739387 -1.43304565 -0.73739242]
 [ 1.34956726 -1.43304565 -1.08521903 -0.04173919  0.30608742]
 [-0.04173919  0.65391403 -0.04173919 -1.08521903 -1.43304565]]


# Q5. Multiply a the following 5x3 matrix by a 3x2 matrix
hint: @ or np.matmul

In [ ]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
## matrix multiplaction
c = np.matmul(a, b)
print(c)
a @ b

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

# Q6. Create random vector of size 10 and replace the maximum value by 0
hint: np.argmax

In [ ]:
u = np.random.randint(100, size=(10))
print (u)
v = (np.argmax(u))
print(v)
u[v] = 0
print(u)

[58 38 92 63 33 71 84 83 55 65]
2
[58 38  0 63 33 71 84 83 55 65]


# Q7. Find the closest value 

hint: get the absolute difference between Z and v using `np.abs`, and find the location of the smallest difference using `.argmin()`

In [ ]:
v = 3.2
Z = np.arange(100)

# find the value that is closest to 3.2 in vector Z
y = np.abs(Z-v)
print(y)
index = y.argmin()
print(Z[index])

[ 3.2  2.2  1.2  0.2  0.8  1.8  2.8  3.8  4.8  5.8  6.8  7.8  8.8  9.8
 10.8 11.8 12.8 13.8 14.8 15.8 16.8 17.8 18.8 19.8 20.8 21.8 22.8 23.8
 24.8 25.8 26.8 27.8 28.8 29.8 30.8 31.8 32.8 33.8 34.8 35.8 36.8 37.8
 38.8 39.8 40.8 41.8 42.8 43.8 44.8 45.8 46.8 47.8 48.8 49.8 50.8 51.8
 52.8 53.8 54.8 55.8 56.8 57.8 58.8 59.8 60.8 61.8 62.8 63.8 64.8 65.8
 66.8 67.8 68.8 69.8 70.8 71.8 72.8 73.8 74.8 75.8 76.8 77.8 78.8 79.8
 80.8 81.8 82.8 83.8 84.8 85.8 86.8 87.8 88.8 89.8 90.8 91.8 92.8 93.8
 94.8 95.8]
3


## Q8. Find the indexes where the values are even

hint: np.where

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# your implementation
indices  = np.where(arr%2 == 0)[0]
print(indices) # it should print [1,3,5,7]

[1 3 5 7]
